fix git pre-commit hook
ensure js is minified

diff --git a/hooks/pre-commit b/hooks/pre-commit
--- a/hooks/pre-commit
+++ b/hooks/pre-commit
@@ -1,3 +1,11 @@
 #!/bin/sh
 
-make
+MINFILE=js/librecast.min.js
+
+if [ `wc -l ${MINFILE} | awk '{ print $1 }'` -gt 1 ];
+then
+	echo "${MINFILE} not minified.  Aborting commit."
+	exit 1
+fi
+
+make lint
